[project]
name = "plantilla-proyecto-python"
version = "0.14.2"
description = "Plantilla para organizar proyectos que usan Python aplicando mejores prácticas de desarrollo."
authors = ["Alejandro Perez Londoño <perezl.alejandro@gmail.com>"]
readme = "README.md"

requires-python = ">=3.14,<3.15"

dependencies = [
    "pydantic-settings>=2.12.0",
    "loguru>=0.7.3",
    "icecream>=2.1.9",
]

[dependency-groups]
dev = [
    "ty>=0.0.12",
    "ruff>=0.14.13",
    "pip-audit>=2.10.0",
    "pre-commit>=4.5.1",
    "commitizen>=4.11.6",
]
tests = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
]
docs = [
    "mkdocs>=1.6.1",
    "mkdocstrings>=1.0.0",
    "mkdocstrings-python>=2.0.1",
    "mkdocs-autorefs>=1.4.3",
    "mkdocs-material>=9.7.1",
    "mkdocs-include-markdown-plugin>=7.2.0",
]

[project.optional-dependencies]
dvc = [
    "dvc[s3]>=3.66.1",
]
nb = [
    "marimo[recommended]>=0.19.4",
    "auto-mix-prep>=0.2.0",
]

[tool.uv]
default-groups = "all"

[tool.ty.analysis]
respect-type-ignore-comments = true

[tool.ty.environment]
python-platform = "all"  # Assume that the source code can run on any platform

[tool.ty.terminal]
error-on-warning = false
output-format = "full"

[tool.ty.src]
respect-ignore-files = true  # Automatically exclude files that are ignored by .ignore and .gitignore
include = ["src", "tests"]
exclude = [".venv"]

[tool.ty.rules]


[tool.ruff]
line-length = 88
src = ["src", "test"]
exclude = ["notebooks"]

[tool.ruff.lint]
select = [
  "A",   # builtins
  "B",   # bugbear
  "COM", # commas
  "C90", # mccabe
  "E",   # pycodestyle
  "F",   # pyflakes
  "D",   # pydocstyle
  "I",   # isort
  "N",   # naming
  "PL",  # pylint
  "UP",  # pyupgrade
  "S",   # bandit
]
ignore = [
  "COM812",  # trailing comma missing ...
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "S101",  # asserts allowed in tests
]

[tool.ruff.lint.extend-per-file-ignores]
"__init__.py" = ["D104"]  # allow missing docstring in public package

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
docstring-code-format = true
docstring-code-line-length = "dynamic"

[tool.ruff.lint.isort]
known-first-party = ["configuracion", "logger"]

[tool.ruff.lint.mccabe]
max-complexity = 6

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver2"
version_provider = "uv"
update_changelog_on_bump = true
major_version_zero = true
version_files = [
    "notebooks/00 - Ejemplo.py:__version__",
    "src/__init__.py:__version__",
    "tests/test_version.py:__version__",
]

[tool.marimo.runtime]
pythonpath = ["src"]
