name: CI - Check and Test

on:
  pull_request:
    branches:
      - main

jobs:
  check-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.4.10"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras

      - name: Run mypy
        run: uv run mypy

      - name: Run Ruff
        run: uv run ruff check --output-format=github .

      - name: Run pip-audit
        run: uv run pip-audit

      - name: Run tests
        run: uv run pytest tests

      - name: Update requirements' files
        run: sh write-requirements.sh
